name: Pirates
main: com.Satrosity.Clans.Clans
version: 2.0.5
commands:
  pirate:
    description: All team commands
    usage: |
           Incorrect usage of /<command>. Examples:
           /<command> - lists commands
  p:
    description: Sends a message to team members
    usage: |
           Incorrect usage of /<command>. Examples:
           /<command> - lists commands
  cap:
    description: Starts a siege on a team's area
    usage: |
           Incorrect usage of /<command>. Examples:
           /<command> - lists commands
  capture:
    description: Starts a siege on a team's area
    usage: |
           Incorrect usage of /<command>. Examples:
           /<command> - lists commands
permissions:
    Pirate.*:
        description: Gives access to all commands
        children:
            Pirate.kick: true
            Pirate.create: true
            Pirate.invite: true
            Pirate.accept: true
            Pirate.reject: true
            Pirate.list: true
            Pirate.info: true
            Pirate.online: true
            Pirate.tktoggle: true
            Pirate.kick: true
            Pirate.rankcreate: true
            Pirate.rankset: true
            Pirate.rankrename: true
            Pirate.rankinfo: true
            Pirate.rankpermission: true
            Pirate.rankdelete: true
            Pirate.disband: true
            Pirate.tag: true
            Pirate.color: true
            Pirate.motd: true
            Pirate.teamchat: true
            Pirate.leave: true
            Pirate.area.claim: true
            Pirate.area.info: true
            Pirate.area.upgrade: true
            Pirate.area.list: true
            Pirate.area.upgrade: true
            Pirate.area.list: true
            Pirate.area.capture: true
            Pirate.score: true
            Pirate.topscores: true
            Pirate.cape: true
    Pirate.kick:
        description: Allows you to kick a user from your team.
        default: op
    Pirate.create:
        description: Allows you to create a team.
        default: op
    Pirate.invite:
        description: Allows you to invite to a team.
        default: op
    Pirate.accept:
        description: Allows you to join a team.
        default: op
    Pirate.reject:
        description: Allows you to reject a team's invite.
        default: op
    Pirate.list:
        description: Allows you to list teams.
        default: op
    Pirate.info:
        description: Allows you to see a team's info.
        default: op
    Pirate.online:
        description: Allows you to see a team's online players.
        default: op
    Pirate.tktoggle:
        description: Allows you to toggle team killing options.
        default: op
    Pirate.rankcreate:
        description: Allows you to create a team rank.
        default: op
    Pirate.rankdelete:
        description: Allows you to create a team rank.
        default: op
    Pirate.rankset:
        description: Allows you to set a player's team rank.
        default: op
    Pirate.rankrename:
        description: Allows you to rename a team rank.
        default: op
    Pirate.rankinfo:
        description: Allows you to see a rank's properties.
        default: op
    Pirate.rankpermission:
        description: Allows you to set a rank's permissions.
        default: op
    Pirate.disband:
        description: Allows you to disband your team.
        default: op
    Pirate.tag:
        description: Allows you to set your team's tag in chat.
        default: op
    Pirate.color:
        description: Allows you to set your team's color.
        default: op
    Pirate.motd:
        description: Allows you to set your team's motd.
        default: op
    Pirate.teamchat:
        description: Allows you to use team chat.
        default: op
    Pirate.leave:
        description: Allows you to leave the team.
        default: op
    Pirate.area.claim:
        description: Allows you to claim an area.
        default: op
    Pirate.area.info:
        description: Allows you to see area info.
        default: op
    Pirate.area.upgrade:
        description: Allows you to upgrade an area.
        default: op
    Pirate.area.list:
        description: Allows you to see your captured areas.
        default: op
    Pirate.area.capture:
        description: Allows you to besiege other team's areas.
        default: op
    Pirate.score:
        description: Allows to see the score of teams.
        default: op
    Pirate.topscores:
        description: Allows to see the top scoring teams.
        default: op
    Pirate.cape:
        description: Allows to set the team cape.
        default: op
